// <auto-generated />
using System;
using KiraYonetimi.DataAcsses.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KiraYonetimi.API.Migrations
{
    [DbContext(typeof(KiraContext))]
    partial class KiraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.ApartType", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApartTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PkId");

                    b.ToTable("ApartTypes");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.ApartUser", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApartId")
                        .HasColumnType("integer");

                    b.Property<int>("ApartUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserPkId")
                        .HasColumnType("uuid");

                    b.HasKey("PkId");

                    b.HasIndex("UserPkId")
                        .IsUnique();

                    b.ToTable("ApartUsers");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Apartment", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApartBlock")
                        .HasColumnType("integer");

                    b.Property<int>("ApartFloor")
                        .HasColumnType("integer");

                    b.Property<int>("ApartId")
                        .HasColumnType("integer");

                    b.Property<int>("ApartNo")
                        .HasColumnType("integer");

                    b.Property<bool>("ApartOwnerOrTenant")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApartStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("ApartTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ApartTypePkId")
                        .HasColumnType("uuid");

                    b.Property<int>("ApartUserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ApartUserPkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PkId");

                    b.HasIndex("ApartTypePkId");

                    b.HasIndex("ApartUserPkId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Invoice", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApartId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ApartPkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApartUserPkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApartmentPkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("InvoiceMonth")
                        .HasColumnType("integer");

                    b.Property<Guid>("InvoicePkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InvoiceStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("InvoiceYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PkId");

                    b.HasIndex("ApartUserPkId");

                    b.HasIndex("ApartmentPkId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Message", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserPkId")
                        .HasColumnType("uuid");

                    b.HasKey("PkId");

                    b.HasIndex("UserPkId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Payment", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InvoicePkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserPkId")
                        .HasColumnType("uuid");

                    b.HasKey("PkId");

                    b.HasIndex("InvoicePkId");

                    b.HasIndex("UserPkId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.User", b =>
                {
                    b.Property<Guid>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlakaNo")
                        .HasColumnType("text");

                    b.Property<bool>("Role")
                        .HasColumnType("boolean");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PkId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.ApartUser", b =>
                {
                    b.HasOne("KiraYonetimi.Entities.Entities.User", "User")
                        .WithOne("ApartUser")
                        .HasForeignKey("KiraYonetimi.Entities.Entities.ApartUser", "UserPkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Apartment", b =>
                {
                    b.HasOne("KiraYonetimi.Entities.Entities.ApartType", "ApartType")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartTypePkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiraYonetimi.Entities.Entities.ApartUser", "ApartUser")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartUserPkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartType");

                    b.Navigation("ApartUser");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Invoice", b =>
                {
                    b.HasOne("KiraYonetimi.Entities.Entities.ApartUser", "ApartUser")
                        .WithMany("Invoices")
                        .HasForeignKey("ApartUserPkId");

                    b.HasOne("KiraYonetimi.Entities.Entities.Apartment", "Apartment")
                        .WithMany("Invoices")
                        .HasForeignKey("ApartmentPkId");

                    b.Navigation("ApartUser");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Message", b =>
                {
                    b.HasOne("KiraYonetimi.Entities.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserPkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Payment", b =>
                {
                    b.HasOne("KiraYonetimi.Entities.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoicePkId");

                    b.HasOne("KiraYonetimi.Entities.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserPkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.ApartType", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.ApartUser", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Apartment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("KiraYonetimi.Entities.Entities.User", b =>
                {
                    b.Navigation("ApartUser");

                    b.Navigation("Messages");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
